
'DiagramaSecuenciaCU36.plantuml

' Flujo: Búsqueda de bolsines y visualización en el mapa con GPS Tracker modelo XTR-4500L
' 1. EB: selecciona la opción para consultar la ubicación de uno o varios bolsines.
' 2. Sistema: busca y muestra la CM del usuario logueado.
' 3. Sistema: busca los bolsines en estado Enviado cuya CM origen es igual a la CM del usuario logueado.
' 4. Sistema: solicita al dispositivo GPS Tracker los datos de localización de los bolsines.
' 5. Sistema: recibe del dispositivo GPS Tracker los datos de localización de cada uno de esos bolsines (ver
' observación 1).
' 6. Sistema: muestra sobre un mapa la posición de los bolsines, habilitando la opción de seleccionar un bolsín del
' mapa o filtrar por número de precinto o CM destino.
' 7. EB: selecciona un bolsín del mapa.
' 8. Sistema: consulta si se desea enviar un correo electrónico al Gerente de Comisión Médica destino para informar
' la ubicación del Bolsín.
' 9. EB: confirma el envío del correo electrónico.
' 10. Sistema: busca la dirección de correo electrónico del GCM destino.
' 11. Sistema: para informar número de bolsín, fecha y hora de última actualización, y las coordenadas del bolsín, se
' incluye al Caso de Uso 31 Notificar ubicación de bolsín. Informa la ejecución exitosa del caso de uso 31. Fin del
' caso de uso

'IMPORTANTE NO BORRAR PLS
' NO se puede poner caracteristicas en los nombres de las entidades
'ejemplo: Usuario logueado, sesion actual. Se usa
' L:Usuario, A:Sesion, etc.
'Clase nombrada: NombreClase : Clase

@startuml test
autonumber

actor ":Encargado Bolsin" as EB
boundary ":PantSegBolsines" as P
control ":GestorSegBolsines" as G
entity "A:Sesion" as S
entity "L:Usuario" as U
entity "L:Empleado" as E

entity ":Bolsin" as B #FFD1DC
entity "S:Bolsin" as Bs 
entity ":Comision Medica" as CM
entity ":Empleado" as Em #FFD1DC
entity "S:Comision Medica" as CMs
entity ":Rol" as R 
entity ":CambioDeEstadoBolsin" as cEstB #FFD1DC

entity "A:CambioDeEstadoBolsin" as estAB
entity "A:EstadoBolsin" as estB

' interfaz clase fabricacion pura
boundary "GPS Tracker" as GPS 
actor "Mapa" as Map
participant "CU31" as CU31




' 1. EB: selecciona la opción para consultar la ubicación de uno o varios bolsines.
EB -> P: opConsultarUbicBolsines()
P-> P: habilitarVentana()
P-> G: opConsultarUbicBolsines() 

' 2. Sistema: busca y muestra la CM del usuario logueado.
G-> G: buscarCMUsuarioLogueado()
G -> S: buscarCMUsuarioLogueado
S-> U: obtenerEmpleado()
U-> E: obtenerNombreCM()
E -> CM: obtenerNombreCM()
E -> CM: obtenerCodigoCM()
G-> P: mostrarNombreCM()

' 3. Sistema: busca los bolsines en estado Enviado cuya CM origen es igual a la CM del usuario logueado.
G-> G: buscarBolsines()
group Bolsines en estado Enviado [mientras haya bolsines]
    G -> B: buscarBolsinesEnEstadoEnviado()
    B -> cEstB: sosActual()
    cEstB -> estAB: sosActual()
    estAB-> estB: sosEnviado()
    G-> B: esTuCMDeOrigen()
    G-> B: obtenerNumeroPrecinto()
end

' 4. Sistema: solicita al dispositivo GPS Tracker los datos de localización de los bolsines.
' 5. Sistema: recibe del dispositivo GPS Tracker los datos de localización de cada uno de esos bolsines
G-> G: buscarDatosLocalizacionBolsines()
G-> GPS: obtenerDatosLocalizacion()

' 6. Sistema: muestra sobre un mapa la posición de los bolsines, habilitando la opción de seleccionar un bolsín del
' mapa o filtrar por número de precinto o CM destino.
GPS-> Map: obtenerDatosLocalizacion()
G-> P: mostrarLocalizacionBolsin()




' 7. EB: selecciona un bolsín del mapa.
G->P: solicitarSeleccionBolsin()
EB-> P: tomarSeleccionBolsin()
P-> G: tomarSeleccionBolsin()

' 8. Sistema: consulta si se desea enviar un correo electrónico al Gerente de Comisión Médica destino para informar
' la ubicación del Bolsín.
G->P: mostrarOpEnviarMail()

' 9. EB: confirma el envío del correo electrónico.
EB-> P: tomarConfirmacionEnvioMail()
P-> G: tomarConfirmacionEnvioMail()
G-> B: obtenerCMDestino()

' 10. Sistema: busca la dirección de correo electrónico del GCM destino.
G->G: buscarMailGerente()

group Empleados CM Destino [mientras haya empleados]
    G-> Em: obtenerEmpleado()
    Em -> CMs: esTuCM()
    Em -> R: sosGerente()
    Em-> Em: obtenerMail()
end

G-> G: enviarMailGerente()
G-> P: mostrarMensajeEnvioMail()

' 11. Sistema: para informar número de bolsín, fecha y hora de última actualización, y las coordenadas del bolsín, se
G -[#blue,dashed]-> CU31: <<include>> llamarCUNotificacionBolsin()
G->G: finCU()

@end

