@startuml
autonumber "<b>00-"
skinparam style strictuml
skinparam ranking as actores

skinparam sequence {
    ParticipantBackgroundColor #EBF3F9
    ParticipantBorderColor #336699
    ParticipantFontName Arial
    ParticipantFontSize 11
    ActorBackgroundColor #FFE6CC
    ActorBorderColor #D79B00
}

skinparam entityBackgroundColor #F5F5F5
skinparam entityBorderColor #666666
skinparam controlBackgroundColor #E2EFDA
skinparam controlBorderColor #375623
skinparam boundaryBackgroundColor #FFF2CC
skinparam boundaryBorderColor #7F6000

skinparam sequenceParticipant {
    roundcorner 100
}

title Diagrama de Secuencia: CU 36 - Consultar seguimiento de bolsines

actor ":EncargadoBolsines" as EB
boundary ":InterfazSeguimiento" as UI <<boundary>>
control ":GestorSeguimientoBolsines" as Ctrl <<control>>
entity "activa:Sesion" as Sesion <<entity>>
entity "logueado:Usuario" as User <<entity>>
entity "logueado:Empleado" as EmpLog <<entity>>
entity ":ComisionMedica" as CMOrig <<entity>>
entity ":Bolsin" as BolsinAux <<entity>>
entity ":CambioEstadoBolsin" as CEBolsin <<entity>>
entity "A:CambioEstadoBolsin" as ACEBolsin <<entity>>
actor ":GPSTracker" as GPS
actor ":ServidorGoogleMaps" as Maps
entity "elegida:Bolsin" as Bolsin <<entity>> #FCE4D6
entity "cmBolsinSeleccionado:ComisionMedica" as CMDest <<entity>>
entity ":Empleado" as EmpCorp <<entity>>
participant "CU 31: Notificar ubicación de bolsín" as CU_Notif

EB -> UI : seleccionarConsultarUbicacion()
activate UI

UI -> UI : habilitarVentana()
activate UI
deactivate UI

UI -> Ctrl : consultarSeguimientoBolsines()
activate Ctrl

Ctrl -> Ctrl : obtenerUsuarioLogueado()
activate Ctrl
    Ctrl -> Sesion : getUsuarioSesion()
    activate Sesion
        Sesion -> User : getEmpleado()
        activate User
            User -> EmpLog : getCM()
            activate EmpLog
                activate EmpLog
                deactivate EmpLog
            deactivate EmpLog
        deactivate User
    deactivate Sesion
deactivate Ctrl

Ctrl -> UI : mostrarCMUsuario()

Ctrl -> Ctrl : buscarBolsinesEnviados()
activate Ctrl
    Ctrl -> BolsinAux : buscarBolsinesEnviados()
    activate CMOrig
        loop [BúsquedaBolsines] [Mientras haya bolsines]
            CMOrig -> BolsinAux : verificarCorrespondencia(cmOrigen)
            activate BolsinAux
                BolsinAux -> BolsinAux : esTuCMOrigen(cmOrigen)
                activate BolsinAux
                deactivate BolsinAux
                BolsinAux -> BolsinAux : sosEnviado()
                activate BolsinAux
                deactivate BolsinAux
            deactivate BolsinAux
        end
    deactivate CMOrig
deactivate Ctrl

Ctrl -> Ctrl : consultarUbicacionesGPS()
activate Ctrl
    Ctrl -> GPS : *getBolsinLocation(apiKey, bolsinId, cmOrigen)
    activate GPS
    deactivate GPS
deactivate Ctrl

Ctrl -> Ctrl : generarMapa()
activate Ctrl
    Ctrl -> Maps : obtenerMapaConPosiciones(listaBolsinesFiltrados)
    activate Maps
    deactivate Maps
deactivate Ctrl

Ctrl -> UI : mostrarMapaYFiltros()
deactivate Ctrl

EB -> UI : seleccionarBolsinDelMapa()

UI -> Ctrl : tomarSeleccionBolsin(bolsinId)
activate Ctrl

Ctrl -> Ctrl : validarEnvioCorreoGCM()
activate Ctrl
deactivate Ctrl

Ctrl -> UI : solicitarConfirmacionEnvio()
deactivate Ctrl

EB -> UI : confirmarEnvioCorreo()

UI -> Ctrl : procesarEnvioNotificacion(bolsinId)
activate Ctrl

Ctrl -> Ctrl : obtenerComisionDestino()
activate Ctrl
    Ctrl -> Bolsin : identificarComisionDestino()
    activate Bolsin
        Bolsin -> CMDest : obtenerCMDestino()
        activate CMDest
          CMDest -> CMDest : getNombre()
          activate CMDest
          deactivate CMDest
        deactivate CMDest
        
    deactivate Bolsin
deactivate Ctrl

Ctrl -> Ctrl : buscarEmailGCM()
activate Ctrl
    Ctrl -> CMDest : buscarEmailGCM()
    activate CMDest
        loop [BúsquedaEmails] [Mientras haya empleados]
            CMDest -> EmpCorp : esTuCM(cmDestino)
            activate EmpCorp
            deactivate EmpCorp
            CMDest -> EmpCorp : sosGCM()
            activate EmpCorp
            deactivate EmpCorp
            CMDest -> EmpCorp : getEmail()
            activate EmpCorp
            deactivate EmpCorp
        end
    deactivate CMDest
deactivate Ctrl

Ctrl -> Ctrl : llamarCUNotificarUbicacion()
activate Ctrl
deactivate Ctrl

Ctrl -> CU_Notif : «include»
activate CU_Notif
deactivate CU_Notif

Ctrl -> UI : informarEjecucionExitosa()
deactivate Ctrl

UI -> EB : mostrarMensajeExito()
deactivate UI

Ctrl -> Ctrl : finCU()

@enduml