@startuml Maquina de Estados Remito
[*] -> Creado : 15. Generar Remito/new()
Creado ---> EnBolsinSaliente : \n\n19. Generar Bolsin/20. Modificar Bolsin/asignarABolsin()
EnBolsinSaliente --> Creado : 20. Modificar Bolsin/21. Eliminar Bolsin/quitar()
EnBolsinSaliente --> EnBolsinEnviado : 27. Registrar el retiro de bolsines/enviar()
EnBolsinEnviado --> Recibido : 28. Registrar recepcion de bolsin/recibir()
Recibido ---> AceptadoParcial : 31. Registrar Revision de Documentación/aceptar()\n[faltaDoc=SI]
Recibido ---> Aceptado : 31. Registrar Revision de Documentación/aceptar()\n[faltaDoc=NO]
Creado --> Cancelado : 17. Cancelar Remito/cancelar()
Cancelado --> [*]
Aceptado --> [*]
AceptadoParcial --> [*]