@startuml usecaseDiagram
left to right direction

actor "Encargado de bolsines" as EB
actor "Gerente de comision medica" as GM
actor "Usuario" as U

usecase "19.Generar bolsin" as U19
usecase "20.Modificar bolsin" as U20
usecase "21.Eliminar bolsin" as U21
usecase "22.Consultar bolsin" as U22
usecase "5. Iniciar sesion" as U5
usecase "37. Generar reporte de bolsines en transito" as U37
usecase "38. Generar estadistica de movimiento de bolsines" as U38

EB --|>U
GM --|>U

U --> U5
EB --> U19
EB --> U20
EB --> U21
EB --> U22

GM --> U37
GM --> U38
@enduml