@startuml Maquina de Estados Bolsin
skinparam style strictuml

state Creado
state Cerrado
state Enviado
state "Recibido en CM destino" as Recibido
state "De baja" as DeBaja

[*] --> Creado : 19. Generar Bolsín / new()
Creado --> Cerrado : 39. Cerrar Bolsín / cerrar()
Cerrado --> Creado : 40. Reabrir Bolsín / reabrir()

Creado --> DeBaja : 21. Eliminar Bolsín / eliminar()
Cerrado --> DeBaja : 21. Eliminar Bolsín / eliminar()

Cerrado --> Enviado : 27. Registrar el retiro de bolsines / enviar()
Enviado --> Recibido : 28. Registrar recepción de bolsín / recibir()

DeBaja --> [*]
Recibido --> [*]
@enduml